version: '3'
services:
  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: "nginx"
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/src:/usr/share/nginx/html
